name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u --deep --target newest --pre -f "/defichain|^@defichain\/.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f1a7646cead32c950d90344a4fb5d4e926972a8f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: Bump @defichain dependencies
          commit-message: Bump @defichain dependencies
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain` dependencies to the latest release.
          branch: defichain-dependencies/bump-deps
